// Generated by scripts/scrape-portfolio.ts — edit titles/alt text as needed.
export type PortfolioItem = {
  id: string;
  category: "photo" | "video" | "design";
  kind: "image" | "video-embed";
  cloudinaryPublicId?: string;
  embedUrl?: string;
  title: string;
  alt: string;
};

export const portfolioItems: PortfolioItem[] = [
  {
    "id": "photo-1",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/unscch3dikbiz9gvs3ox",
    "title": "Fotografía 1",
    "alt": "Fotografía 1"
  },
  {
    "id": "photo-2",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/drpzejkddxuopmox8dm9",
    "title": "Fotografía 2",
    "alt": "Fotografía 2"
  },
  {
    "id": "photo-3",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/wcf3bfa2ztru2on2vxbs",
    "title": "Fotografía 3",
    "alt": "Fotografía 3"
  },
  {
    "id": "photo-4",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/u3crkbffggu16nqh33so",
    "title": "Fotografía 4",
    "alt": "Fotografía 4"
  },
  {
    "id": "photo-5",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lxj1a7g3t0k0mxqb3yzf",
    "title": "Fotografía 5",
    "alt": "Fotografía 5"
  },
  {
    "id": "photo-6",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/busohurirp1ksmci56sd",
    "title": "Fotografía 6",
    "alt": "Fotografía 6"
  },
  {
    "id": "photo-7",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ggci6eoj60yml8nlg7n7",
    "title": "Fotografía 7",
    "alt": "Fotografía 7"
  },
  {
    "id": "photo-8",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/asbhrbbrv8r92df7wncq",
    "title": "Fotografía 8",
    "alt": "Fotografía 8"
  },
  {
    "id": "photo-9",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/uejw8lxigndxvwfvzkeu",
    "title": "Fotografía 9",
    "alt": "Fotografía 9"
  },
  {
    "id": "photo-10",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/umhd7kd8wxtyx4gt7alv",
    "title": "Fotografía 10",
    "alt": "Fotografía 10"
  },
  {
    "id": "photo-11",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ardcpyiyf30iflik8f1w",
    "title": "Fotografía 11",
    "alt": "Fotografía 11"
  },
  {
    "id": "photo-12",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ok8omepfxmecewrbfx6p",
    "title": "Fotografía 12",
    "alt": "Fotografía 12"
  },
  {
    "id": "photo-13",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/umsfca1n6ylnezzkqrzl",
    "title": "Fotografía 13",
    "alt": "Fotografía 13"
  },
  {
    "id": "photo-14",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/jmk1toxtb5vk6i8zfdcy",
    "title": "Fotografía 14",
    "alt": "Fotografía 14"
  },
  {
    "id": "photo-15",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/epgxkefubmawycawywhb",
    "title": "Fotografía 15",
    "alt": "Fotografía 15"
  },
  {
    "id": "photo-16",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/txco4aldybqejnbedaax",
    "title": "Fotografía 16",
    "alt": "Fotografía 16"
  },
  {
    "id": "photo-17",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fmxfv2czkm6vii2qovko",
    "title": "Fotografía 17",
    "alt": "Fotografía 17"
  },
  {
    "id": "photo-18",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/v10vbczncxrr0nthazsg",
    "title": "Fotografía 18",
    "alt": "Fotografía 18"
  },
  {
    "id": "photo-19",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hzh6jewspaubh5lga8pl",
    "title": "Fotografía 19",
    "alt": "Fotografía 19"
  },
  {
    "id": "photo-20",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/dcvn4bf4oo0or6vagv17",
    "title": "Fotografía 20",
    "alt": "Fotografía 20"
  },
  {
    "id": "photo-21",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ycd7nexjev73srg9btnu",
    "title": "Fotografía 21",
    "alt": "Fotografía 21"
  },
  {
    "id": "photo-22",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/slg5ayin2bf6iibzl7xd",
    "title": "Fotografía 22",
    "alt": "Fotografía 22"
  },
  {
    "id": "photo-23",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/kkhisclrchwme3dymmd4",
    "title": "Fotografía 23",
    "alt": "Fotografía 23"
  },
  {
    "id": "photo-24",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/obcd78gqzj304kizvbcj",
    "title": "Fotografía 24",
    "alt": "Fotografía 24"
  },
  {
    "id": "photo-25",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ygkjxovtrpttq9hyo7a9",
    "title": "Fotografía 25",
    "alt": "Fotografía 25"
  },
  {
    "id": "photo-26",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/wg9dz7k95jrosih00hsk",
    "title": "Fotografía 26",
    "alt": "Fotografía 26"
  },
  {
    "id": "photo-27",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/oocciyxbjln3sww7swyt",
    "title": "Fotografía 27",
    "alt": "Fotografía 27"
  },
  {
    "id": "photo-28",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/c5xu3p62ncr3rn5livni",
    "title": "Fotografía 28",
    "alt": "Fotografía 28"
  },
  {
    "id": "photo-29",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/cs6gvbgsj0vykrl9cpkt",
    "title": "Fotografía 29",
    "alt": "Fotografía 29"
  },
  {
    "id": "photo-30",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/wh258ppqpihtwxj3ya81",
    "title": "Fotografía 30",
    "alt": "Fotografía 30"
  },
  {
    "id": "photo-31",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/sunfjygkxewrdypaxken",
    "title": "Fotografía 31",
    "alt": "Fotografía 31"
  },
  {
    "id": "photo-32",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/rf6ndiq0knwhqb6xpi55",
    "title": "Fotografía 32",
    "alt": "Fotografía 32"
  },
  {
    "id": "photo-33",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/sl2sv8upjhs4jgph21rx",
    "title": "Fotografía 33",
    "alt": "Fotografía 33"
  },
  {
    "id": "photo-34",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/znjn68c7kpyssst3q6zn",
    "title": "Fotografía 34",
    "alt": "Fotografía 34"
  },
  {
    "id": "photo-35",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/f90zyd25pbhm0kej1qld",
    "title": "Fotografía 35",
    "alt": "Fotografía 35"
  },
  {
    "id": "photo-36",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/d6ynzcdmfuljmhs1rr0r",
    "title": "Fotografía 36",
    "alt": "Fotografía 36"
  },
  {
    "id": "photo-37",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fbjm93vme9vkp61miy5j",
    "title": "Fotografía 37",
    "alt": "Fotografía 37"
  },
  {
    "id": "photo-38",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/eeotec15uzpihbj3iyll",
    "title": "Fotografía 38",
    "alt": "Fotografía 38"
  },
  {
    "id": "photo-39",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/tfn3anjg4dt8tse7afjq",
    "title": "Fotografía 39",
    "alt": "Fotografía 39"
  },
  {
    "id": "photo-40",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/v3tweehpux0qcogbajca",
    "title": "Fotografía 40",
    "alt": "Fotografía 40"
  },
  {
    "id": "photo-41",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hlqh5vvbfd0r1ywnrvxc",
    "title": "Fotografía 41",
    "alt": "Fotografía 41"
  },
  {
    "id": "photo-42",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/e5fr6thymedk0frhiiip",
    "title": "Fotografía 42",
    "alt": "Fotografía 42"
  },
  {
    "id": "photo-43",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/twmrvvpdcgjnqcwg9krp",
    "title": "Fotografía 43",
    "alt": "Fotografía 43"
  },
  {
    "id": "photo-44",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/j4bfafxbggjmhy53a700",
    "title": "Fotografía 44",
    "alt": "Fotografía 44"
  },
  {
    "id": "photo-45",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/uvew0azcgczetvjcicjt",
    "title": "Fotografía 45",
    "alt": "Fotografía 45"
  },
  {
    "id": "photo-46",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hw27kpuhjvoy3x7b0q5q",
    "title": "Fotografía 46",
    "alt": "Fotografía 46"
  },
  {
    "id": "photo-47",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hcoxotm8qcoypx8ynvie",
    "title": "Fotografía 47",
    "alt": "Fotografía 47"
  },
  {
    "id": "photo-48",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/gdj2l0jheryjomqpgnqq",
    "title": "Fotografía 48",
    "alt": "Fotografía 48"
  },
  {
    "id": "photo-49",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/basju2wc9srm9mp35j1q",
    "title": "Fotografía 49",
    "alt": "Fotografía 49"
  },
  {
    "id": "photo-50",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/qpzg5kzylvnwlehz20et",
    "title": "Fotografía 50",
    "alt": "Fotografía 50"
  },
  {
    "id": "photo-51",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lod4n1h7ban8t58lvdpk",
    "title": "Fotografía 51",
    "alt": "Fotografía 51"
  },
  {
    "id": "photo-52",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/yuknzyjnd7hbgr0seh4v",
    "title": "Fotografía 52",
    "alt": "Fotografía 52"
  },
  {
    "id": "photo-53",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/szmurwwow6cyqbujcd76",
    "title": "Fotografía 53",
    "alt": "Fotografía 53"
  },
  {
    "id": "photo-54",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lmgiy6vpfw3uctwt6vnz",
    "title": "Fotografía 54",
    "alt": "Fotografía 54"
  },
  {
    "id": "photo-55",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hvdw3f6ohtfpwqdesxc6",
    "title": "Fotografía 55",
    "alt": "Fotografía 55"
  },
  {
    "id": "photo-56",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/w4yxmicb6jihmjekba6d",
    "title": "Fotografía 56",
    "alt": "Fotografía 56"
  },
  {
    "id": "photo-57",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/q3egs5ntay8ifphucqbt",
    "title": "Fotografía 57",
    "alt": "Fotografía 57"
  },
  {
    "id": "photo-58",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hl37nbxk7muq64fwtpx9",
    "title": "Fotografía 58",
    "alt": "Fotografía 58"
  },
  {
    "id": "photo-59",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/f7wocrmvosapybjvzap1",
    "title": "Fotografía 59",
    "alt": "Fotografía 59"
  },
  {
    "id": "photo-60",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/siuty4cyixs3fbg9rgfo",
    "title": "Fotografía 60",
    "alt": "Fotografía 60"
  },
  {
    "id": "photo-61",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/v6eebgfdfq8c7inlf7f7",
    "title": "Fotografía 61",
    "alt": "Fotografía 61"
  },
  {
    "id": "photo-62",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/oa0y5mhfierojsux6juh",
    "title": "Fotografía 62",
    "alt": "Fotografía 62"
  },
  {
    "id": "photo-63",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/gymaolbtexb968g4cfkt",
    "title": "Fotografía 63",
    "alt": "Fotografía 63"
  },
  {
    "id": "photo-64",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/g390hmzwzg4inrv2ezie",
    "title": "Fotografía 64",
    "alt": "Fotografía 64"
  },
  {
    "id": "photo-65",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/pmtxdurptv65kumshxsj",
    "title": "Fotografía 65",
    "alt": "Fotografía 65"
  },
  {
    "id": "photo-66",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fdmriu8biwxxt5ukplss",
    "title": "Fotografía 66",
    "alt": "Fotografía 66"
  },
  {
    "id": "photo-67",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ybklo7nqiiys7ak0gjcj",
    "title": "Fotografía 67",
    "alt": "Fotografía 67"
  },
  {
    "id": "photo-68",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/yaztddrmm0os4aero6au",
    "title": "Fotografía 68",
    "alt": "Fotografía 68"
  },
  {
    "id": "photo-69",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/grigvfoelsvgmzny6bsk",
    "title": "Fotografía 69",
    "alt": "Fotografía 69"
  },
  {
    "id": "photo-70",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/kkc5rgxcfwdi1awbkkaw",
    "title": "Fotografía 70",
    "alt": "Fotografía 70"
  },
  {
    "id": "photo-71",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/xvor0ahyvzkjyfkfndoh",
    "title": "Fotografía 71",
    "alt": "Fotografía 71"
  },
  {
    "id": "photo-72",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/m9cr06jxcdqh5tugpbng",
    "title": "Fotografía 72",
    "alt": "Fotografía 72"
  },
  {
    "id": "photo-73",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/c5lzpgx8ftl0jbd3nwfh",
    "title": "Fotografía 73",
    "alt": "Fotografía 73"
  },
  {
    "id": "photo-74",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/tcc6mcaxnlvnn1mlhnpz",
    "title": "Fotografía 74",
    "alt": "Fotografía 74"
  },
  {
    "id": "photo-75",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/eujcoxgn1vd0qikycdlh",
    "title": "Fotografía 75",
    "alt": "Fotografía 75"
  },
  {
    "id": "photo-76",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/n1f8voljfkpgni2tmzay",
    "title": "Fotografía 76",
    "alt": "Fotografía 76"
  },
  {
    "id": "photo-77",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/iwvpcgxkhxfrwd5iukiv",
    "title": "Fotografía 77",
    "alt": "Fotografía 77"
  },
  {
    "id": "photo-78",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fwza3nwwmda3otmk1ien",
    "title": "Fotografía 78",
    "alt": "Fotografía 78"
  },
  {
    "id": "photo-79",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/vaf3vfqfzngya6vr2o3j",
    "title": "Fotografía 79",
    "alt": "Fotografía 79"
  },
  {
    "id": "photo-80",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/chjgsusbc3e9mt8dxpoo",
    "title": "Fotografía 80",
    "alt": "Fotografía 80"
  },
  {
    "id": "photo-81",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/vrc6bgqctszxe3dhvzsl",
    "title": "Fotografía 81",
    "alt": "Fotografía 81"
  },
  {
    "id": "photo-82",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lsndxzr7z1cztchze7nq",
    "title": "Fotografía 82",
    "alt": "Fotografía 82"
  },
  {
    "id": "photo-83",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/n5ypjawellhiomxnd0b1",
    "title": "Fotografía 83",
    "alt": "Fotografía 83"
  },
  {
    "id": "photo-84",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/gtwdl1wfioze2ax4zhzo",
    "title": "Fotografía 84",
    "alt": "Fotografía 84"
  },
  {
    "id": "photo-85",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/cbmr0cqsscr7hmnricak",
    "title": "Fotografía 85",
    "alt": "Fotografía 85"
  },
  {
    "id": "photo-86",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/o9awpmfybofd643jant5",
    "title": "Fotografía 86",
    "alt": "Fotografía 86"
  },
  {
    "id": "photo-87",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/i9yanhbjufsmagknlmby",
    "title": "Fotografía 87",
    "alt": "Fotografía 87"
  },
  {
    "id": "photo-88",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/vwuqtnhsnz5dxohsckiz",
    "title": "Fotografía 88",
    "alt": "Fotografía 88"
  },
  {
    "id": "photo-89",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/kcstdgwexr17dslhhcwq",
    "title": "Fotografía 89",
    "alt": "Fotografía 89"
  },
  {
    "id": "photo-90",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/rhztg3dgw3suj2sr1zrm",
    "title": "Fotografía 90",
    "alt": "Fotografía 90"
  },
  {
    "id": "photo-91",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ei0axquolpnxsn9wqvoy",
    "title": "Fotografía 91",
    "alt": "Fotografía 91"
  },
  {
    "id": "photo-92",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ocapyhw9apgprzqxykgm",
    "title": "Fotografía 92",
    "alt": "Fotografía 92"
  },
  {
    "id": "photo-93",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/kqqnxkkqacak2navhybd",
    "title": "Fotografía 93",
    "alt": "Fotografía 93"
  },
  {
    "id": "photo-94",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/abrcpnbpa8lvi4amj8p3",
    "title": "Fotografía 94",
    "alt": "Fotografía 94"
  },
  {
    "id": "photo-95",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/egnw3msxoo5sv8fzv3wo",
    "title": "Fotografía 95",
    "alt": "Fotografía 95"
  },
  {
    "id": "photo-96",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/jhrfmf2lczogvjvwjdlg",
    "title": "Fotografía 96",
    "alt": "Fotografía 96"
  },
  {
    "id": "photo-97",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/bkae6xolzckfvbaevvfy",
    "title": "Fotografía 97",
    "alt": "Fotografía 97"
  },
  {
    "id": "photo-98",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/k7xkpqp1kljrueyzfztb",
    "title": "Fotografía 98",
    "alt": "Fotografía 98"
  },
  {
    "id": "photo-99",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/bd7pcgl2shlfxarq4rma",
    "title": "Fotografía 99",
    "alt": "Fotografía 99"
  },
  {
    "id": "photo-100",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ckyev7mrd16w7laaisna",
    "title": "Fotografía 100",
    "alt": "Fotografía 100"
  },
  {
    "id": "photo-101",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fpoqk1rnb5fn57vilvly",
    "title": "Fotografía 101",
    "alt": "Fotografía 101"
  },
  {
    "id": "photo-102",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/qaz3ofkkhvuqlim5ass2",
    "title": "Fotografía 102",
    "alt": "Fotografía 102"
  },
  {
    "id": "photo-103",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/mgo45pcjao8tzxy2uok5",
    "title": "Fotografía 103",
    "alt": "Fotografía 103"
  },
  {
    "id": "photo-104",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/gkchfpvrqrdafs56trfu",
    "title": "Fotografía 104",
    "alt": "Fotografía 104"
  },
  {
    "id": "photo-105",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/llywzfpb9txey1so41pl",
    "title": "Fotografía 105",
    "alt": "Fotografía 105"
  },
  {
    "id": "photo-106",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/y9m9yhexe0houx9rlk4h",
    "title": "Fotografía 106",
    "alt": "Fotografía 106"
  },
  {
    "id": "photo-107",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/d29z55jl7mqiq2zoecdn",
    "title": "Fotografía 107",
    "alt": "Fotografía 107"
  },
  {
    "id": "photo-108",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/fjld1xjwb5fxy2gdt9sa",
    "title": "Fotografía 108",
    "alt": "Fotografía 108"
  },
  {
    "id": "photo-109",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/wdwntjfnauuugewpzcvf",
    "title": "Fotografía 109",
    "alt": "Fotografía 109"
  },
  {
    "id": "photo-110",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hfzcuf8ggziyiiybhors",
    "title": "Fotografía 110",
    "alt": "Fotografía 110"
  },
  {
    "id": "photo-111",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/bdoajodbxubumb4cogch",
    "title": "Fotografía 111",
    "alt": "Fotografía 111"
  },
  {
    "id": "photo-112",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/emhsrxgoxdfblux8dnvo",
    "title": "Fotografía 112",
    "alt": "Fotografía 112"
  },
  {
    "id": "photo-113",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lj8gv8luo5lngi0pujx3",
    "title": "Fotografía 113",
    "alt": "Fotografía 113"
  },
  {
    "id": "photo-114",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/z0dgceburbsrjw0uzlmk",
    "title": "Fotografía 114",
    "alt": "Fotografía 114"
  },
  {
    "id": "photo-115",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ydyimmpk82sy56kxfakv",
    "title": "Fotografía 115",
    "alt": "Fotografía 115"
  },
  {
    "id": "photo-116",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/m7upjs9s2oizfymrb9ez",
    "title": "Fotografía 116",
    "alt": "Fotografía 116"
  },
  {
    "id": "photo-117",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/dpfcxn2r4geyhzdvm7ek",
    "title": "Fotografía 117",
    "alt": "Fotografía 117"
  },
  {
    "id": "photo-118",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/xb4hw2ui5ozyzwfkkmnw",
    "title": "Fotografía 118",
    "alt": "Fotografía 118"
  },
  {
    "id": "photo-119",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ppfyvmqyxcityjnqcyts",
    "title": "Fotografía 119",
    "alt": "Fotografía 119"
  },
  {
    "id": "photo-120",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/rpz9zllsgfoj0rgtbtqy",
    "title": "Fotografía 120",
    "alt": "Fotografía 120"
  },
  {
    "id": "photo-121",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ednssplmdwm5dglwymwg",
    "title": "Fotografía 121",
    "alt": "Fotografía 121"
  },
  {
    "id": "photo-122",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/hgpebmfbp9eqwyd0xlsn",
    "title": "Fotografía 122",
    "alt": "Fotografía 122"
  },
  {
    "id": "photo-123",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/rfvkfr871smaj2prkz1b",
    "title": "Fotografía 123",
    "alt": "Fotografía 123"
  },
  {
    "id": "photo-124",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/vmliz7omxailwaawhfva",
    "title": "Fotografía 124",
    "alt": "Fotografía 124"
  },
  {
    "id": "photo-125",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ocpyt6xrsiqx3cojgmr7",
    "title": "Fotografía 125",
    "alt": "Fotografía 125"
  },
  {
    "id": "photo-126",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/c6fni2urxrzt6xp74hod",
    "title": "Fotografía 126",
    "alt": "Fotografía 126"
  },
  {
    "id": "photo-127",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/dz7aoagcpg1nnx9rvhnk",
    "title": "Fotografía 127",
    "alt": "Fotografía 127"
  },
  {
    "id": "photo-128",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/lyllpw7kl1gcb1oaunlx",
    "title": "Fotografía 128",
    "alt": "Fotografía 128"
  },
  {
    "id": "photo-129",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/dhvs5r5wbd83apqfyvw4",
    "title": "Fotografía 129",
    "alt": "Fotografía 129"
  },
  {
    "id": "photo-130",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/q9znu3k5zmlr3swnz9oy",
    "title": "Fotografía 130",
    "alt": "Fotografía 130"
  },
  {
    "id": "photo-131",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/ff8veclbni9gh2r7vxet",
    "title": "Fotografía 131",
    "alt": "Fotografía 131"
  },
  {
    "id": "photo-132",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/qomihrapepm2pshsba8i",
    "title": "Fotografía 132",
    "alt": "Fotografía 132"
  },
  {
    "id": "photo-133",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/jnuj0bmcgne64xciwypz",
    "title": "Fotografía 133",
    "alt": "Fotografía 133"
  },
  {
    "id": "photo-134",
    "category": "photo",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/photo/jg8hwoowi3pyuysugjpa",
    "title": "Fotografía 134",
    "alt": "Fotografía 134"
  },
  {
    "id": "video-1",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/3doMGgsg4tF/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 1",
    "alt": "Video 1"
  },
  {
    "id": "video-2",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/9Q_MiNvYzV7/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 2",
    "alt": "Video 2"
  },
  {
    "id": "video-3",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/3hHKXiXWHAY/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 3",
    "alt": "Video 3"
  },
  {
    "id": "video-4",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/RmZYBr5-7FK/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 4",
    "alt": "Video 4"
  },
  {
    "id": "video-5",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/EE4HqqNk-JK/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 5",
    "alt": "Video 5"
  },
  {
    "id": "video-6",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/W-3Lk8NIaX-/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 6",
    "alt": "Video 6"
  },
  {
    "id": "video-7",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/VdcFK6-3Qos/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 7",
    "alt": "Video 7"
  },
  {
    "id": "video-8",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/-2oSEMEqmA-/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 8",
    "alt": "Video 8"
  },
  {
    "id": "video-9",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/29fLXpgeDhP/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 9",
    "alt": "Video 9"
  },
  {
    "id": "video-10",
    "category": "video",
    "kind": "video-embed",
    "embedUrl": "https://www-ccv.adobe.io/v1/player/ccv/Tp7noBibqkr/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
    "title": "Video 10",
    "alt": "Video 10"
  },
  {
    "id": "design-1",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/fn651buowvcsxwehhhqk",
    "title": "Diseño 1",
    "alt": "Diseño 1"
  },
  {
    "id": "design-2",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/b5iiaj9avzeicnzd2o3s",
    "title": "Diseño 2",
    "alt": "Diseño 2"
  },
  {
    "id": "design-3",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/yr4dfhivvgyi34yifuj6",
    "title": "Diseño 3",
    "alt": "Diseño 3"
  },
  {
    "id": "design-4",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/cwusrowd2dlke1iop5qg",
    "title": "Diseño 4",
    "alt": "Diseño 4"
  },
  {
    "id": "design-5",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/qenowf3ile9szmr0znpc",
    "title": "Diseño 5",
    "alt": "Diseño 5"
  },
  {
    "id": "design-6",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/j2uf3yx4haoietvq8ihw",
    "title": "Diseño 6",
    "alt": "Diseño 6"
  },
  {
    "id": "design-7",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/hvnszgvvdgxzrt3uteym",
    "title": "Diseño 7",
    "alt": "Diseño 7"
  },
  {
    "id": "design-8",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/c8txoblyiicsorqel8mm",
    "title": "Diseño 8",
    "alt": "Diseño 8"
  },
  {
    "id": "design-9",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/oacqzhbykmsbf9zi5rsa",
    "title": "Diseño 9",
    "alt": "Diseño 9"
  },
  {
    "id": "design-10",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/qhrixn12o52nbiqpzjxi",
    "title": "Diseño 10",
    "alt": "Diseño 10"
  },
  {
    "id": "design-11",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/hyr9zehspws9zzio3yzg",
    "title": "Diseño 11",
    "alt": "Diseño 11"
  },
  {
    "id": "design-12",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/dv7mldfe865mv3vj8qjn",
    "title": "Diseño 12",
    "alt": "Diseño 12"
  },
  {
    "id": "design-13",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/nwkil6jpib7k1zemtimh",
    "title": "Diseño 13",
    "alt": "Diseño 13"
  },
  {
    "id": "design-14",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/hllwrxoqzd6f8fksys3x",
    "title": "Diseño 14",
    "alt": "Diseño 14"
  },
  {
    "id": "design-15",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/zxy9didvwduiadih7nsp",
    "title": "Diseño 15",
    "alt": "Diseño 15"
  },
  {
    "id": "design-16",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/rralixeqsuwbxcf9tlyp",
    "title": "Diseño 16",
    "alt": "Diseño 16"
  },
  {
    "id": "design-17",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/ckhmkt9hid7oawfeg3ar",
    "title": "Diseño 17",
    "alt": "Diseño 17"
  },
  {
    "id": "design-18",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/b02qu52s81piqoottyae",
    "title": "Diseño 18",
    "alt": "Diseño 18"
  },
  {
    "id": "design-19",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/s4jrr9jf9ky5zdp66ysv",
    "title": "Diseño 19",
    "alt": "Diseño 19"
  },
  {
    "id": "design-20",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/icpd2fxlxsw1mmrs67nf",
    "title": "Diseño 20",
    "alt": "Diseño 20"
  },
  {
    "id": "design-21",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/mkifxmtuqbkgwdibcmzz",
    "title": "Diseño 21",
    "alt": "Diseño 21"
  },
  {
    "id": "design-22",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/o2uyf3bfjrtzojqm5bad",
    "title": "Diseño 22",
    "alt": "Diseño 22"
  },
  {
    "id": "design-23",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/bsxvrxjrdeqrtdaqjudq",
    "title": "Diseño 23",
    "alt": "Diseño 23"
  },
  {
    "id": "design-24",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/iffzneqfgnldyblvtejg",
    "title": "Diseño 24",
    "alt": "Diseño 24"
  },
  {
    "id": "design-25",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/x5ij2l2sddmngtogmwnf",
    "title": "Diseño 25",
    "alt": "Diseño 25"
  },
  {
    "id": "design-26",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/mobhrrjhmoa7bdcuzmco",
    "title": "Diseño 26",
    "alt": "Diseño 26"
  },
  {
    "id": "design-27",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/kzthwznjoatnv1hru7gv",
    "title": "Diseño 27",
    "alt": "Diseño 27"
  },
  {
    "id": "design-28",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/rrfcqj2gb6c1amkxooh2",
    "title": "Diseño 28",
    "alt": "Diseño 28"
  },
  {
    "id": "design-29",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/myj5en9sz9sp9dq5mgmh",
    "title": "Diseño 29",
    "alt": "Diseño 29"
  },
  {
    "id": "design-30",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/lqggei02grjq5564vvxb",
    "title": "Diseño 30",
    "alt": "Diseño 30"
  },
  {
    "id": "design-31",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/z6u64imbumfhzvvmyk01",
    "title": "Diseño 31",
    "alt": "Diseño 31"
  },
  {
    "id": "design-32",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/gw8h2yj3oafcasnaqo7b",
    "title": "Diseño 32",
    "alt": "Diseño 32"
  },
  {
    "id": "design-33",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/deilvxwtbdqf10uqs3lu",
    "title": "Diseño 33",
    "alt": "Diseño 33"
  },
  {
    "id": "design-34",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/ksloxbhp7shln45lu6fc",
    "title": "Diseño 34",
    "alt": "Diseño 34"
  },
  {
    "id": "design-35",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/pgiza4sh1lp4m49qd5ic",
    "title": "Diseño 35",
    "alt": "Diseño 35"
  },
  {
    "id": "design-36",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/qqvcscbaktfofxpbws73",
    "title": "Diseño 36",
    "alt": "Diseño 36"
  },
  {
    "id": "design-37",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/ijitxwska7b3r4vvpp2t",
    "title": "Diseño 37",
    "alt": "Diseño 37"
  },
  {
    "id": "design-38",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/ba8mmc8uvqxicmfsxdi4",
    "title": "Diseño 38",
    "alt": "Diseño 38"
  },
  {
    "id": "design-39",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/uedaonsazc6ehj6qcfcm",
    "title": "Diseño 39",
    "alt": "Diseño 39"
  },
  {
    "id": "design-40",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/jujo8cvta54tfbrfsulv",
    "title": "Diseño 40",
    "alt": "Diseño 40"
  },
  {
    "id": "design-41",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/nlmoyhqckk1s2xjm95cc",
    "title": "Diseño 41",
    "alt": "Diseño 41"
  },
  {
    "id": "design-42",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/jvexontv9w4pl0dbui2v",
    "title": "Diseño 42",
    "alt": "Diseño 42"
  },
  {
    "id": "design-43",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/gbldk9uaewiou3tapp0b",
    "title": "Diseño 43",
    "alt": "Diseño 43"
  },
  {
    "id": "design-44",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/kpihxzijg3qgprdffpld",
    "title": "Diseño 44",
    "alt": "Diseño 44"
  },
  {
    "id": "design-45",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/wg8uyhewbmfj2sfvmwth",
    "title": "Diseño 45",
    "alt": "Diseño 45"
  },
  {
    "id": "design-46",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/dxt0ktfjgpmibjah1a76",
    "title": "Diseño 46",
    "alt": "Diseño 46"
  },
  {
    "id": "design-47",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/toje3fggu0s51zupzuoe",
    "title": "Diseño 47",
    "alt": "Diseño 47"
  },
  {
    "id": "design-48",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/doqhhxf761b9iqehtxfr",
    "title": "Diseño 48",
    "alt": "Diseño 48"
  },
  {
    "id": "design-49",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/gtyxafdkxvqqcejjupxn",
    "title": "Diseño 49",
    "alt": "Diseño 49"
  },
  {
    "id": "design-50",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/ynlrtmirzsmlnmllkvs7",
    "title": "Diseño 50",
    "alt": "Diseño 50"
  },
  {
    "id": "design-51",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/gqaekxujq5ndv3o3hbvj",
    "title": "Diseño 51",
    "alt": "Diseño 51"
  },
  {
    "id": "design-52",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/p3la3ko4otzjysvogj0n",
    "title": "Diseño 52",
    "alt": "Diseño 52"
  },
  {
    "id": "design-53",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/jo6n8onu77qew7zs2mij",
    "title": "Diseño 53",
    "alt": "Diseño 53"
  },
  {
    "id": "design-54",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/fcodnjhooqbdjualybbv",
    "title": "Diseño 54",
    "alt": "Diseño 54"
  },
  {
    "id": "design-55",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/jwi3si3xborxdfgvmy5k",
    "title": "Diseño 55",
    "alt": "Diseño 55"
  },
  {
    "id": "design-56",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/l4ahseovcsrgji8t6ndh",
    "title": "Diseño 56",
    "alt": "Diseño 56"
  },
  {
    "id": "design-57",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/pjnm9nclpijxlanjujy7",
    "title": "Diseño 57",
    "alt": "Diseño 57"
  },
  {
    "id": "design-58",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/kiqjxmzh67cekjamioh6",
    "title": "Diseño 58",
    "alt": "Diseño 58"
  },
  {
    "id": "design-59",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/vteo08v9nu4taskx3jdu",
    "title": "Diseño 59",
    "alt": "Diseño 59"
  },
  {
    "id": "design-60",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/heltlkwm5ucoopnaydnv",
    "title": "Diseño 60",
    "alt": "Diseño 60"
  },
  {
    "id": "design-61",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/skxowjvuxqxdsewrod6a",
    "title": "Diseño 61",
    "alt": "Diseño 61"
  },
  {
    "id": "design-62",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/joher4s6yzktteiwymkq",
    "title": "Diseño 62",
    "alt": "Diseño 62"
  },
  {
    "id": "design-63",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/dxr4ursw4290gldf39fp",
    "title": "Diseño 63",
    "alt": "Diseño 63"
  },
  {
    "id": "design-64",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/w5uvtmbvhox4ezagnisw",
    "title": "Diseño 64",
    "alt": "Diseño 64"
  },
  {
    "id": "design-65",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/od7ikwmw5bsbrfza8uad",
    "title": "Diseño 65",
    "alt": "Diseño 65"
  },
  {
    "id": "design-66",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/o0xlsv50frdvalprlzv0",
    "title": "Diseño 66",
    "alt": "Diseño 66"
  },
  {
    "id": "design-67",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/gvlnfpjm9e7zrzxns6hi",
    "title": "Diseño 67",
    "alt": "Diseño 67"
  },
  {
    "id": "design-68",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/qtnj9llir0bio2x341js",
    "title": "Diseño 68",
    "alt": "Diseño 68"
  },
  {
    "id": "design-69",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/mlznrfd2yc0ccxqo7ldp",
    "title": "Diseño 69",
    "alt": "Diseño 69"
  },
  {
    "id": "design-70",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/mbatbkudvdrtluygbudi",
    "title": "Diseño 70",
    "alt": "Diseño 70"
  },
  {
    "id": "design-71",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/wvjuokfdrqikkszk6cma",
    "title": "Diseño 71",
    "alt": "Diseño 71"
  },
  {
    "id": "design-72",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/p9orkbvavbzvowsdfadt",
    "title": "Diseño 72",
    "alt": "Diseño 72"
  },
  {
    "id": "design-73",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/u5lpl3qvnsud7w7wt6fj",
    "title": "Diseño 73",
    "alt": "Diseño 73"
  },
  {
    "id": "design-74",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/zmlwwtg3jhqgnfncnadp",
    "title": "Diseño 74",
    "alt": "Diseño 74"
  },
  {
    "id": "design-75",
    "category": "design",
    "kind": "image",
    "cloudinaryPublicId": "dizayn/design/itryupwrcg3gnj2crfvi",
    "title": "Diseño 75",
    "alt": "Diseño 75"
  }
];
